apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  creationTimestamp: null
  name: cicd-event-listener
  namespace: quarkus-demo-cicd
spec:
  podTemplate: {}
  serviceAccountName: pipeline
  triggers:
    - name: ci-dryrun-from-push
      bindings:
        - ref: github-push-binding
      interceptors:
        - github:
            secretRef:
              namespace: quarkus-demo-cicd
              secretKey: webhook-secret-key
              secretName: gitops-webhook-secret
        - cel:
            filter: (header.match('X-GitHub-Event', 'push') && body.repository.full_name == 'adnan-drina/quarkus-demo-app-gitops')
            overlays:
              - expression: body.ref.split('/')[2]
                key: ref
      template:
        name: ci-dryrun-from-push-template
    - name: app-ci-build-from-push-quarkus-demo-app
      bindings:
        - ref: quarkus-demo-dev-app-quarkus-demo-app-quarkus-demo-app-binding
        - ref: github-push-binding
      interceptors:
        - github:
            secretRef:
              namespace: quarkus-demo-cicd
              secretKey: webhook-secret-key
              secretName: webhook-secret-quarkus-demo-dev-quarkus-demo-app
        - cel:
            filter: (header.match('X-GitHub-Event', 'push') && body.repository.full_name == 'adnan-drina/quarkus-demo-app')
            overlays:
            - expression: body.ref.split('/')[2]
              key: ref
      template:
        name: app-ci-template
status:
  configuration:
    generatedName: ""
