apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: argocd-user
  namespace: quarkus-demo-cicd
spec:
  encryptedData:
    ARGOCD_PASSWORD: AgBeVp80Htue2oBsm3qI30Dmj9L9qlrybk0hU5AP+V/qXdvbYJTZf4iucuUbVvhRe+QBJOANptzcglWKNazZkEW1VejGPtI8QlUO3jQXNz97J5WajsUjJ0eg/oAE3g7YnGdT8tbmkbC2AjePe7sib1zOhTXewlifHBL6jksMDB/V5in7/ztNEDVpS8M5egcv/Hca45Rfh/UAMVzIqv1TEOm4BMka1DhSw66/JRnt2XPK+eCsQ/jGW/0ERE9HXs5OoPu0LCDO933ndlLSCbqQyXwOxtRAdiscvaDkONHgvK3BOuS6rGXCXb5bnM2MNJLGoAT1gcw0AFzN3JvTmG3/M25XX0D7KzHmtLqqqdx2bOeaQlbcDURrROb5Jr7mN9Qk+7lg6As8iq+8WeWFkvA1LNGWTTz91jiiGJMMmTUuhTbgZH10cdlEOn7yLkpF4oTbdJ8hT671LJBXXMa7vTy1I63OVbN2oBN5mG/f4FUZY+R+Nz09Bdfirzv7PwQ3eikdWU3rP9LRwT84KNwcrAO426a/f6FZ6NYSrwPi+ctxGYYilG69pzxRonTrUnbJ7vBXLk6xa5nVr03ybCC6VQ0mNmpXv4sfqJV3FLp8oiDJHJm8L/Xic82ytnrKWUuTrGxabsvkoatzakjF9jo9EBYv1lQ4Y/yWRIWYPei9rlLhEcyeNSwD+rchFA2sajmfF/VryUNVLqxYbM78hSUnhav33736gmoooE+/kJncBHxWrOWO2Q==
    ARGOCD_USERNAME: AgCyVYvQQco89WIxS1Rh4XvcZ2FLnrjAeM9ItdPGdDt2yEWVvQhdpk1UF51iuvPF/p4f7CESZkQKU0DJlL7D751vU+vtlA2tEII/5o4qLu/TYBwb49LYzkCX3pZhcoXYhmM6T9kTK8zPEbJ9jTQP12K1AHlIXNZLF/F+pf9WI0ENTjA92M1GqYgLK9P9DDPgicBwsj+xscwNzu1GuOSmaToAwLvKER2VvZi9KKjPwgfvaEaGnt4R1NCBtMM/qDnu390HjF7PtdNEZiIWJu/ATtHoxf8bPsxeFzuJ7DONsYb2nxjcG5AnfL1Akjk5Jqip+WVtaskQFSl3y3fKGsy3v3K5ZyTQyT8ZFL8rwm9/uTYv06IPxFburZuHnb5DIQ4Pnyv1FQ8g6hBpYtZ44fMcM13M3B/8pOnFXkkOAXpkFjpL2t8uArer8TL31coFrzL0zM3IiVO5/gFCB7Gaf5P2abbURXtVoFWXPIVYfjy1oDSjYeLgOuykDEqZlUIy+6OlXdlkxO6LAqtegBXmfYEPY7SZtoSWktKI2dd3gEJZ7Kn1Pgoj7hkZGLW4W0vt7BfS2pjMgDRcEQ+xns9Nt2vMaowbl24R2YpzaCIGKNNjB0ZoVV8ekrjjLxhHnqIKCBfp3DHXia1iLXX6l+Ip0lN0tvA/AXJqMYRC8Aexu5oEcD4sLXrSOmmCR6Oc+IMjRIkxb8Lmw2T7mA==
  template:
    metadata:
      creationTimestamp: null
      name: argocd-user
      namespace: quarkus-demo-cicd

