apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: quarkus-demo-cicd
spec:
  encryptedData:
    .dockerconfigjson: AgAJHJT816GC9+VD42eeeFmjJkTW3EAzcPxAMKIxo2IpuY9j6STUIR2HntS6Nw6eP35vm2MTl5PfmHalTRVZtcaVc+BbZEQd6d3BJF4ecZcizlNj5/0dVebTG9w0edEhThuhT+nUk45hTT39gy2+BKgqAWgUcXE2XbkTirDoW6DBc5W8QiWwM90bFPAuIh72w6gKByCp76NavGlYH1U8hWsdICWNm0mSPCBihhqDYdW4CchZ9fRdQSkd54i9nIJIXdUotZeu3YTXXqYAyElRsE91yaWZ3BN4J9UXABrEfJvDT6wxP/6qYlorF1AL3sUCIIgzIIBnXdwuMwOc+JwD0Qp/Xm9Tj4Nrx06qVCtIF/skfjyN2DbYc/jELcuO/BMteHwVhmeukJkuu2PxHRXyucf8D5GvThza+TZ6VkvGC0zXCQ/VleRgcVnYY7hhqe+96Nv6JpAP9P7AA2QanK1gVbvpEqIgd2LtEokS6NSz8MY6A/nNsEJHB5jA1sSdhjY/z+aR/FlT3nKpDp6bEl0DsMBLtCsR9mKY7SBPxkcVnTs+YoynR9i3QnqjyccDlGMDDxv+RXrdo9PVnSJiCLXpo05v9j+F1IFgZrP2IbBBHMDaNEJ3t1sUmF842ry/20vgBEOAxj0f3kfVO+r+V9tZrkNwws4hPa1L2Ghs9wF2EMBnUzKs+hurrLZtHAJJgQXPP4Q7pu4yiWtC386H/Y8gicJENcixzoZvAgPa/unksfzMb9Q6LBelFn98QA6TomvIRl9bzx85kxF3qmLIEh2/O+9/315tXnw7bqpx1rCKlG50wcJJb7c32v7Ij4oQW9kCdO5pCNon/vPqSMYf/mFuuS44EsjK4MiUf7f68cFllV7Rkk68fQjRXBU=
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: quarkus-demo-cicd
    type: kubernetes.io/dockerconfigjson
