apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: git-host-access-token
  namespace: quarkus-demo-cicd
spec:
  encryptedData:
    token: AgCWvPGUu7ZhxXqktk3E7hCRzkpRl9czQMWbirW7RJEcbFKCBXVE48AlKbNfqHafY5tCqnHR72hKG9cKXWujm0/cqXJw0/bd1MbeuINWVowRVdb44O0yrZvAG5GVYJZOa3AJb1MSd+pZK5OI/U5/jvPA8dldcQwq4a9U6w83q4sPy+xInuXk+RqrBAFYcGHruMbkThYWSOdeg5v50obxyDiHNZN16+JImT6+R+KE4wae8HTkSY7a4joKdzqAYkoWkBuuk0WZGVEGFDS9URKzoGTeeV/cEd3n9hC63wf4EGmmMDucs+vs3igY5cA6z0b6A5sRnzMgQXS7mhZt+577xTEJrJWgiB74Z36XeqL58EgwAQ8qS3Rew0r/C36Nm9m6KlTflAyQZcExhohaL3IheVVpP+4xtAjUXmibC3oGDGnO1rfNLZXli5qpDvnEoybadvT2pvEIIpJFERx+1o7jrQadkb+wk4OD+xSCtfYIoYADb2wOQxBgrZu4MErANQkbhrjlwIyh1+v90yOPTLsmRFo9JTEwfasZGkM7DFf2o46SQu0c3r1OXkHJN02aobqwahOXNxhRdOL1Gq/7nNNxEeSKReX4cj5naWwHRG855gbgjojF67DcSIvvBoGdCHoQ00CpfeYVKRBSTmvfUcEwuFM1Wz+Y2pQ7iDYGMqqpTuEuSsVggwKdw+F7dYGO6IQQoPUMCBlFqYrTE4D+pSDJtVWK38SeHX023udjMZzyiF2w/moom3W/tENK
  template:
    metadata:
      creationTimestamp: null
      name: git-host-access-token
      namespace: quarkus-demo-cicd
    type: Opaque
