apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: git-host-basic-auth-token
  namespace: quarkus-demo-cicd
spec:
  encryptedData:
    password: AgCKItHsAPAU/H14v+0cC5vi1syNddYJDf6EEtzvC0YkZreBn/rz5ICW3S/eWNbniCJ+TXSG0RnVGy1JAgDOgQcBg72vzAYxAihR7uKwjSxulpHDb1aWHT43mfawkmoNw29QECxUb23GJodaM++5Gcqa+zTG/th8H53mapbAfdMACV/JKTtVhLXKMAHXtONi2onciLL1tpcWseLeJSHJTFjgtRhOlunLFGkMZM6YL9EfAKDoT2HTK/vzDw/Umxb8Gl4WZpEJrRLlOmuxBOJZxxeOAkr2dQHwHrczQqbyb2qgB/yBfHj/B1tBa6xXi/rHLzVoV+xC2WGAHJ07WKO74l+CzeJnCU9KIT5GV7IoM6Ul0Rac5mDGWhEiVPYrKDOw4+5jBafk6sZfIqjCa44UCdzJIzW8rcIPxaoxZFvwR45xiIN8DWIIH11Y6HbtCXiu9AqNeAqxxZZC18jGfgipBgTQrrrzXwI61pLO0C5/XRyt1l0IBfMzei/kKlMFQHrI+dAmmiGmZVNeb2YPkO3vp22E8gz7KXXI2bQnE/BRcYo+C5ocgfNcNEC6rzK9erWocRFYOg7RYoFbawnoA7M1yzNkXF4ESbgrQLTvlqhgyEzYKPUeOxDmQeIgyY6gwayr/vuPh607SxOY6foBpvoxH8JHl0Nc0LUoq+2qqdY4RyhtetuhXhnggkcVsJUAG6eTpwI+ME5veW55qtx4AWy/j2pO7/Qg1YiOauepoOhGCtgHSLQSSLe0GG+c
    username: AgBC5NqR/JXL7ITlrMtZ4vdaxJcNl9Z5KTWIqzrwDNz5TVmopbdwBPBc5Sr1+COkd6m14y7RaVwfB/b0Z/TngK4NyipKl8Vl1II+EQm7GpDQwgEUV+5Tbei/C1xDiydpMSdS5Fhqa2V28fXs6ytQIWdt6y/I4mYAJvhl4iHnFWSQE23vDu9CoZpioXsyMQ/0VZ8XvOufeihqiDgXSMEBSzVbymqimHz6TQCuH2R7bKPu7MooUMrlr3OYvKlPvwn/O9O+Q2tZTKXXpJd2V5qtXgn2fLQWWmoXMECJel4TgldIave0I60Vsh/cfbDAKatzLv6UeLEHh2rXe/Qutes1jOO8fUJ36JGaEkbwT9ffUP4TfjlviKckTqNxXy8XsLdZxQsU40SjI/zlERC7OscpUtunRcz0azcLk3TvgPddhq6K+AsRnZguC0HH6nodP6ngl8EgQZYICMQbeAPe2JvScKYrxIOsULBKMCnIEPDJencudtXGBg4W2H2GBHIoergtWTVuUKfaUa7VOXzR5yagFg7KMxOBA+Y1DT1stFG2htoIZJ8pEpfQg2NY3TtMwXqsvs1guVwEZTdePYrXCQwAIW7JwvAH/ijZjkofKEpRnVVWzjBDKEOOFkpfSGi175MkFnWsFGffel7HEwlcjLslq9i/KUlFlr/NGYsYHon1/SidTSQAxKl92ZH9ksIPodCmXUUGMe6McvA=
  template:
    metadata:
      annotations:
        tekton.dev/git-0: https://github.com
      creationTimestamp: null
      name: git-host-basic-auth-token
      namespace: quarkus-demo-cicd
    type: kubernetes.io/basic-auth
