apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: git-host-basic-auth-token
  namespace: quarkus-demo-cicd
spec:
  encryptedData:
    password: AgA4etsKoQd3OwqUj9E+h2B1/bTeXUQ9++pj6mFLpEjykLUVheP9Bflq+7toWNxTG0foY49LFXFW06gK/R9CMptKhTF3gYwgaEXRr889EjdGTfGIyB5NguynIHtAk5O8u1aOA7SjuMVuHnETjj6gR0D2pb31nib5FSUGg5MmI9y/DhJeGUusLiB90GIOoEz9IBwa1FrlnCq1/MKrNqbn8y+BAimwPg/IV47bxMTBOiiHR81YCRl3V5gbolIJxkKIF6UUNfGoTvcLdKIJhzN2vP/tRSyHadMST3V3AfvQMddC45sfb/S4e/PikGnmTANmviOtZAsuCFLQ7Kbw8GmcZV8Pp5+kEeRIxa047HxY/acXRWWXsFGz6I8WkyNQRZM3Em+P1D4qyCAyk6qTrWI33nkHFRfX2gD9ErstUkZVPoHbm+fM9H3hIqLT9pIC5sELx5KqUiW012uTHLP3p19H/D/qo9LLZoen/AgO0u6oUQs5PJ430jQTC4W/RKS17iDwRVKlMRk/oiVsTzxDQk133P86Gc2z2WKRaG7crVGyECHQgo6xazLr0Skp7ibkMGfbHxxXsNvP4TtKO4zA6blkQsjYzVApI+iwP9SZ/YW6sO6cLH/UjxtRn4R1DV0vWCfXkS6BLWlj+lkgT8sqC591iNNLKhZuX7+wDValdlRa5Gxap7ac3l2b6T+oiCdomYHxpI7WxaCz5OLPTLLilS3qChS9FsrEP7Eusy0kHwIaH3sZ7GjEBYw3+lLD
    username: AgA9g3BiybZYSgoK2KEi97gGvt4oVZUUC8kQMrDS1jI1ouQ+XKjwVsOUC0oFkNslnhPlJy8bWsRkOvhuuMUdWH6BgPRE49ezzjQGCF8afe+0kH1PA/wefoAisLy/+tMqIkr82YI4WOU70huSNSiMakzp7bhPAbiHvtyvYcKjsLv0x5GKEusofB6r184cvk7Cj9cNkpgIQzn8hwlyQT4atlkucAwTtTylX9ZI7SrUKwxBWVVWehz9lIgxr1HMedov1xo3Sn1vaLti4qZuKYepeBZSnFNTtZwLtAKAMK8NolK7j1CFXXqB80EO5PA1q1pDTE0hXuhaSwild9m/I/+nqaPhGYa2l8uTAJa+OqzHJzo5lCS8FoG71A9NnFmec1pqPzVnOaSzMWlaz5uqg/l39roOkms62FwgXvZAY30mvZyK7MhBhY8HWFRYYLbu8F+x+80f5Gn32KQWTsb/pudqETPH4rh/wIC/yMif4ewC3FNIckSDqG/g0sxKLIgY0eZ4rlhRvJTrsfXsh71WxACGY9JsPglCSz/1ompTsCkR7BvS1a9wfihABXJcDL7M+VAjqPyp+Q7+wml5OyVt/jDTy91C0q54yN+qGZbMy6bjLpoDEIMtypo6q1Efrff4MX4ehYvsP0Ou+KaQ5W4VdmwqZysvgNThx7veAldHzbNb3GH+txfegEmbknYeAqXYIE/yn4EuN8VQtlg=
  template:
    metadata:
      annotations:
        tekton.dev/git-0: https://github.com
      creationTimestamp: null
      name: git-host-basic-auth-token
      namespace: quarkus-demo-cicd
    type: kubernetes.io/basic-auth

