apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: quarkus-demo-cicd
spec:
  encryptedData:
    webhook-secret-key: AgCuSNoj1Rd3sAiQC/zYnypQP1ov7Itn5Z042V6vIPN+2Oakw/S/0E+yT+w8cr+ATx14/ava5OZsJEDKYT4Vq8SYjnBwRvyOcLTSebLCow8fdtz5cc/kbBuzznldH7r0TH/Vs/C7epBiMVKh6Z2jwfsOOtSXtZ1jcVqd41aBIoK78q/5YDVpqzc5IbvU79xSni/iph+dZYsrv1U7Ie5fMIOQ4GBkuSECkvUL5djDbTlMXjkG8EKEFkyihXFjM+pSRLPFicZ2IjKn+go65zzmcp1e6ZeWFogSsSKTgabpdXNz8924ilsRfR8bSvG2HtFF5cEiddo7DjWcveBGA4SznpOxuVb6FWvyZbNqV6CVarlGlNHkxY/r3+c9xtQZ8NHSzk3ENR8HEfrKnwX3T76fsr+zCWKttxBm4gbtb38vatxeZylJLvVEVt98s4K0L4F7LwsUcoIABfJMaM7lF5nrUGtj6N55xSYW2JmNPb+Sq+G96ONmccvRJrm67LiJyAgmYLa656vKTqsJIbjtAROdb31xweVWyLond+HgyWWXCYVxOSjEphdAVQ7iNE3KTyhbZLbCIP/EDmpRWR9cJfk+fkyl42gCDsPbuAKyYvkYj9GsTfbz7qdMXxlviQAH3uFkv/LlZVHnwsCGpghgd38f6oMPAv6k2rtg82R4M7b1T9aIYpBYgxS1v+3KC6PVoPULrQLm7yGUu5HsJ59d5mSPn0G4P2qNWQ==
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: quarkus-demo-cicd
    type: Opaque
