apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-secret-quarkus-demo-dev-quarkus-demo-app
  namespace: quarkus-demo-cicd
spec:
  encryptedData:
    webhook-secret-key: AgA4PDkfaFvschTOGcuyBDGLedwcakookVftE780I2BdZIzR74xau0pkbr7XGc0WlxAu0Ot8kfW4Kl0Wk6LS8DNDVVcLOv2MdLBvEKO/5ty+Mo9sZzZa6rf1zeX/BscMhAAYHuXyJMukooJWwvuZbNQa3y6Fyc/wBFImLFVfDFpJCvAZBeIBEU5M4eMFc4ZGcHjIDHxVVf6DW5SykQ3N7nA7ijJLpxSnivnUSpnowdixCV6HeMe0LwcYn4wH6qT/bA3JvBpiZsA2aLY4X2PLv2tUaK/egwcMMPlpk8yAtMZ2Y6ZAat0jHW1cTOuBs9Q4U9+GUeD2XUGE1e2W7VFz+Gs45x3vX1sh7QZ2kCfAolfJBdw1XBu5hIIZ89NSehTX0pqTnrkixSbeEXyAm7Z2VJ1HssIocwQOtaDfO9RzWNKQX+vTuxu4AuXX1sRjlaF/7jrZfAofe0FHk0rzDJ+HXPjwSQLFin9icNKgGVohJ5O/gX8M8+OpUd0m4BiRpiEWgqm0bHz/yWmVPBzcS4jBKBL1Xlcls9IoFIOYqsBDy6nze/VciG4/iPYkGOzN7asmNK3hFV3zhT5k3Sn6Ydu9SHyCQ6UtkC6iFw9g4/eqSNt6aQNGbuRTnr7y2KZl8G+N87/Rcq0vDvaCWnJc8H7Q/GB0lp2oDIBC4qqX/WbB4nsDkNhQMa+b5kLqxwMWefiUjK9UbOTfM85+FZFEQFJdKCxK//7NCQ==
  template:
    metadata:
      creationTimestamp: null
      name: webhook-secret-quarkus-demo-dev-quarkus-demo-app
      namespace: quarkus-demo-cicd
    type: Opaque

