apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: deploy-with-argocd
spec:
  params:
    - name: environment
    - name: argo-app-name
    - name: appImage
    - name: buildRevision
    - name: buildEventRevision
  workspaces:
    - name: config-source

  steps:

    - name: update-yaml
      image: alpine/git:v2.26.2
      workingDir: "$(workspaces.config-source.path)/$(inputs.params.environment)"
      script: |
        #!/usr/bin/env sh
        set -e

        echo $(input.params.buildRevision)
        echo $(input.params.buildEventRevision)

        echo "updating $(workspaces.config-source.path)/$(inputs.params.environment) image to $(inputs.params.appImage)"
        sed -i "s|quay.io/adrina/quarkus-demo-app:main-[a-zA-Z0-9]\\+|$(inputs.params.appImage)|g" 100-deployment.yaml

#        echo "updating all pods in $(inputs.params.environment) to revision $(inputs.params.buildRevision)"
#        sed -i "s#revision: \"[a-zA-Z0-9]\\+\"#revision: \"$(inputs.params.buildRevision)\"#" app.yaml

    - name: commit-push-changes-gitops
      image: alpine/git:v2.26.2
      workingDir: "$(workspaces.config-source.path)"
      script: |
        #!/usr/bin/env sh
        set -e

        git config --global user.email "adnan.drina@gmail.com"
        git config --global user.name "adnan-drina"

        git checkout master
        git status
        git add .
        git commit --allow-empty -m "[tekton] updating image to $(inputs.params.appImage)"
        git push origin master

#    - name: wait-for-argocd-rollout
#      image: argoproj/argocd:v1.7.7
#      script: |
#        #!/usr/bin/env sh
#        set -e
#
#        argocd app sync $(inputs.params.argo-app-name) --insecure
#        argocd app wait $(inputs.params.argo-app-name) --sync --health --operation --insecure
---