apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: maven-package
spec:
  workspaces:
    - name: source
    - name: maven-settings
  steps:
    - name: build
      image: maven:3.6.3-openjdk-11-slim
      workingDir: /workspace/source
      command:
        - /usr/bin/mvn
      args:
        - -Dmaven.repo.local=$(workspaces.source.path)/.m2
        - '-s'
        - $(workspaces.maven-settings.path)/settings.xml
        - -DskipTests
        - clean
        - package