apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  creationTimestamp: null
  name: quarkus-demo-dev-env
  namespace: argocd
spec:
  destination:
    namespace: quarkus-demo-dev
    server: https://kubernetes.default.svc
  project: default
  source:
    path: environments/quarkus-demo-dev/env/overlays
    repoURL: https://github.com/adnan-drina/quarkus-demo-app-gitops.git
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
status:
  health: {}
  summary: {}
  sync:
    comparedTo:
      destination: {}
      source:
        repoURL: https://github.com/adnan-drina/quarkus-demo-app-gitops.git
    status: ""
