apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  creationTimestamp: null
  name: quarkus-demo-dev-app-quarkus-demo-app-quarkus-demo-app-binding
  namespace: quarkus-demo-cicd
spec:
  params:
  - name: imageRepo
    value: quay.io/adrina/quarkus-demo-app
  - name: tlsVerify
    value: "true"
status: {}
