apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: quarkus-demo-app
    app.kubernetes.io/part-of: app-quarkus-demo-app
    app.openshift.io/runtime: quarkus
  name: quarkus-demo-app
  namespace: quarkus-demo-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: quarkus-demo-app
      app.kubernetes.io/part-of: app-quarkus-demo-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
    revisionHistoryLimit: 10
    progressDeadlineSeconds: 600
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: quarkus-demo-app
        app.kubernetes.io/part-of: app-quarkus-demo-app
    spec:
      containers:
      - image: quay.io/adrina/quarkus-demo-app:main-346e769e4653c6d4620102bb8dc4b81428e1f398
        imagePullPolicy: Always
        name: quarkus-demo-app
        ports:
        - containerPort: 8080
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        resources: {}
      serviceAccountName: default
status: {}
