apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: quarkus-demo-app
    app.kubernetes.io/part-of: app-quarkus-demo-app
    app.openshift.io/runtime: quarkus
  name: quarkus-demo-app
  namespace: quarkus-demo-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: quarkus-demo-app
      app.kubernetes.io/part-of: app-quarkus-demo-app
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: quarkus-demo-app
        app.kubernetes.io/part-of: app-quarkus-demo-app
    spec:
      containers:
      - image: quay.io/adrina/quarkus-demo-app:main-a41e8413280a54c74a3ec3016c86b8e56a16bad2
        imagePullPolicy: Always
        name: quarkus-demo-app
        ports:
        - containerPort: 8080
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 45
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 45
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        resources: {}
      serviceAccountName: default
status: {}
