apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: quarkus-demo-app
    app.kubernetes.io/part-of: app-quarkus-demo-app
  name: quarkus-demo-app
  namespace: quarkus-demo-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: quarkus-demo-app
      app.kubernetes.io/part-of: app-quarkus-demo-app
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: quarkus-demo-app
        app.kubernetes.io/part-of: app-quarkus-demo-app
    spec:
      containers:
      - image: quay.io/adrina/quarkus-demo-app:main-315c00350773b4d3560f792d33b0aa0c24b4d307ain-4de5f21e9a8c246de313215922cee9f6afb85ecb-2228696fac59ac30f66b19cda50560a4e7c9f938
        imagePullPolicy: Always
        name: quarkus-demo-app
        ports:
        - containerPort: 8080
        resources: {}
      serviceAccountName: default
status: {}
