apiVersion: v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: quarkus-demo-app
    app.kubernetes.io/part-of: app-quarkus-demo-app
  name: quarkus-demo-app
  namespace: quarkus-demo-dev
spec:
  host:
  path: /
  to:
    kind: Service
    name: quarkus-demo-app
    weight: 100
  port:
    targetPort: 8080
  wildcardPolicy: None