apiVersion: v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: quarkus-demo-app
    app.kubernetes.io/part-of: app-quarkus-demo-app
  name: quarkus-demo-app
  namespace: quarkus-demo-dev
spec:
  path: "/"
  to:
    kind: Service
    name: quarkus-demo-app
  port:
    targetPort: 8080