apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  creationTimestamp: null
  name: app-ci-pipeline
  namespace: quarkus-demo-cicd
spec:
  params:
  - name: REPO_FULLNAME
    type: string
  - name: REPO_NAME
    type: string
  - name: TLSVERIFY
    type: string
  - name: BUILD_EXTRA_ARGS
    type: string
  - name: ARGO_APP_NAME
    type: string
  - name: ENV_CONFIG_LOCATION
    type: string
  - name: IMAGE
    type: string
  - name: IMAGE_REPO
    type: string
  - name: GIT_REF
    type: string
  - name: COMMIT_SHA
    type: string
  - name: COMMIT_DATE
    type: string
  - name: COMMIT_AUTHOR
    type: string
  - name: COMMIT_MESSAGE
    type: string
  - name: GIT_REPO
    type: string
  - name: GITOPS_REPO
    type: string

  tasks:

  - name: clone-source
    params:
    - name: url
      value: $(params.GIT_REPO)
    - name: revision
      value: $(params.GIT_REF)
    - name: deleteExisting
      value: "true"
    taskRef:
      kind: ClusterTask
      name: git-clone
    workspaces:
    - name: output
      workspace: shared-data

  - name: package-app
    taskRef:
      kind: Task
      name: maven
    runAfter:
      - clone-source
    workspaces:
      - name: source
        workspace: shared-data
      - name: maven-settings
        workspace: maven-settings
    params:
      - name: GOALS
        value:
          - -DskipTests
          - clean
          - package
          - -Pnative
#          - -Dmaven.repo.local=$(workspaces.local-maven-repo.path)
#          - -Dquarkus.container-image.insecure=true
#          - -Dquarkus.container-image.registry=example.com
#          - -Dquarkus.container-image.build=true
#          - -Dquarkus.container-image.push=true
#          - -Dquarkus.container-image.group=$(params.imageGroup)
#          - -Dquarkus.container-image.name=$(params.imageName)
#          - package

  - name: unit-tests
    taskRef:
      kind: Task
      name: maven
    runAfter:
      - package-app
    workspaces:
      - name: source
        workspace: shared-data
      - name: maven-settings
        workspace: maven-settings
    params:
      - name: GOALS
        value:
          - test

  - name: code-analysis
    taskRef:
      kind: Task
      name: maven
    runAfter:
      - package-app
    workspaces:
      - name: source
        workspace: shared-data
      - name: maven-settings
        workspace: maven-settings
    params:
      - name: GOALS
        value:
          - sonar:sonar
          - -DskipTests
          - -Dsonar.project.tags=$(params.COMMIT_SHA)

  - name: release-app
    taskRef:
      kind: Task
      name: maven
    runAfter:
      - code-analysis
      - unit-tests
    workspaces:
      - name: source
        workspace: shared-data
      - name: maven-settings
        workspace: maven-settings
    params:
      - name: GOALS
        value:
          - deploy
          - -DskipTests

  - name: build-image
    params:
      - name: TLSVERIFY
        value: $(params.TLSVERIFY)
      - name: BUILD_EXTRA_ARGS
        value: --label=io.openshift.build.commit.author='$(params.COMMIT_AUTHOR)' --label=io.openshift.build.commit.date='$(params.COMMIT_DATE)' --label=io.openshift.build.commit.id='$(params.COMMIT_SHA)' --label=io.openshift.build.commit.message='$(params.COMMIT_MESSAGE)' --label=io.openshift.build.commit.ref='$(params.GIT_REF)'
      - name: IMAGE
        value: $(params.IMAGE)
#      - name: DOCKERFILE
#        value: ./src/main/docker/Dockerfile.native
    runAfter:
      - release-app
    taskRef:
      kind: ClusterTask
      name: buildah
    workspaces:
      - name: source
        workspace: shared-data

  - name: clone-config
    taskRef:
      name: git-clone
      kind: ClusterTask
    workspaces:
      - name: output
        workspace: shared-data
    runAfter:
      - build-image
    params:
      - name: url
        value: $(params.GITOPS_REPO)
      - name: deleteExisting
        value: "true"

  - name: update-manifest
    taskRef:
      name: update-deployment-manifest
    runAfter:
      - clone-config
    params:
      - name: environment
        value: $(params.ENV_CONFIG_LOCATION)
      - name: appImage
        value: $(params.IMAGE)
    workspaces:
      - name: config-source
        workspace: shared-data

  - name: deploy-to-dev
    taskRef:
      name: argocd-task
    runAfter:
      - update-manifest
    params:
      - name: application-name
        value: $(params.ARGO_APP_NAME)
      - name: flags
        value: --grpc-web

  workspaces:
  - description: This workspace will receive the cloned git repo.
    name: shared-data
  - description: This workspace containes Maven settings.
    name: maven-settings
