apiVersion: v1
kind: ConfigMap
metadata:
  name: maven-settings
  namespace: quarkus-demo-cicd
data:
  settings.xml: |
    <?xml version="1.0" encoding="UTF-8"?>
    <settings>
      <profiles>
        <profile>
          <id>sonar</id>
          <activation>
              <activeByDefault>true</activeByDefault>
          </activation>
          <properties>
              <sonar.host.url>https://sonarqube-sonarqube.apps.cluster-7d6e.7d6e.example.opentlc.com/</sonar.host.url>
          </properties>
        </profile>
      </profiles>
      <servers>
        <server>
          <id>nexus</id>
          <username>admin</username>
          <password>admin123</password>
        </server>
      </servers>
      <mirrors>
        <mirror>
          <id>nexus</id>
          <name>nexus</name>
          <url>http://nexus-nexus-repository.apps.cluster-7d6e.7d6e.example.opentlc.com/repository/maven-public/</url>
          <mirrorOf>*</mirrorOf>
        </mirror>
      </mirrors>
    </settings>