apiVersion: v1
kind: ConfigMap
metadata:
  name: maven-settings
  namespace: quarkus-demo-cicd
data:
  settings.xml: |
    <?xml version="1.0" encoding="UTF-8"?>
    <settings>
      <profiles>
        <profile>
          <id>nexus</id>
          <properties>
            <altDeploymentRepository>nexus::http://nexus-nexus-repository.apps.cluster-0b9a.0b9a.example.opentlc.com/repository/maven-releases/</altDeploymentRepository>
            <altReleaseDeploymentRepository>nexus::http://nexus-nexus-repository.apps.cluster-0b9a.0b9a.example.opentlc.com/repository/maven-releases/</altReleaseDeploymentRepository>
            <altSnapshotDeploymentRepository>nexus::http://nexus-nexus-repository.apps.cluster-0b9a.0b9a.example.opentlc.com/repository/maven-snapshots/</altSnapshotDeploymentRepository>
          </properties>
        </profile>
        <profile>
          <id>sonar</id>
          <activation>
              <activeByDefault>true</activeByDefault>
          </activation>
          <properties>
              <sonar.host.url>https://sonarqube-sonarqube.apps.cluster-0b9a.0b9a.example.opentlc.com</sonar.host.url>
              <sonar.login>admin</sonar.login>
              <sonar.password>admin123</sonar.password>
          </properties>
        </profile>
      </profiles>
      <activeProfiles>
        <activeProfile>nexus</activeProfile>
      </activeProfiles>
      <servers>
        <server>
          <id>nexus</id>
          <username>admin</username>
          <password>admin123</password>
        </server>
      </servers>
      <mirrors>
        <mirror>
          <id>nexus</id>
          <name>nexus</name>
          <url>http://nexus-nexus-repository.apps.cluster-0f3b.0f3b.example.opentlc.com/repository/maven-public/</url>
          <mirrorOf>*</mirrorOf>
        </mirror>
      </mirrors>
    </settings>